# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CameraPractice' do
  pod 'SnapKit', '~> 5.0.0'
  pod 'SDWebImage', '~> 5.0', :modular_headers => true
  pod 'SDWebImageWebPCoder', :modular_headers => true
end
